USE QL_DH_GH
GO

--Phân hệ quản trị--
EXEC SP_ADDLOGIN 'QL_DH_GH_QUANTRI', '12345', 'QL_DH_GH'
EXEC sp_addsrvrolemember 'QL_DH_GH_QUANTRI', 'sysadmin';  
GO
--VODANH
EXEC sp_addlogin 'QL_DH_GH_VODANH', '12345', 'QL_DH_GH';  
GO

CREATE USER VODANH FOR LOGIN QL_DH_GH_VODANH
GO

GRANT SELECT, INSERT ON dbo.TAIKHOAN TO VODANH 
GO


-- DOITAC
EXEC sp_addlogin 'QL_DH_GH_DOITAC', '12345', 'QL_DH_GH';  
GO

CREATE USER DOITAC FOR LOGIN QL_DH_GH_DOITAC
GO

GRANT SELECT, UPDATE, INSERT
ON DOITAC
TO DOITAC
--3--
GRANT SELECT
ON HOPDONG
TO DOITAC
--4--
GRANT SELECT, INSERT, UPDATE, DELETE
ON QLTHUCDON
TO DOITAC


--5--
GRANT SELECT
ON DONHANG
TO DOITAC

GRANT SELECT
ON QLDONHANG
TO DOITAC

GRANT SELECT
ON TAIXE(TENTX, SDTTX)
TO DOITAC
--6--
GRANT UPDATE
ON DONHANG(TRANGTHAIDONHANG)
TO DOITAC
--7--
GRANT SELECT, INSERT, UPDATE, DELETE
ON CHINHANH
TO DOITAC
--8--
GRANT SELECT
ON KHACHHANG(TENKH, SDTKH)
TO DOITAC

GRANT EXECUTE ON OBJECT::sp_DT_ThemChiNhanh TO DOITAC
GRANT EXECUTE ON OBJECT::DT_UPDATE_GiASP TO DOITAC
GRANT EXECUTE ON OBJECT::Sp_DT_THEMSP to doitac
GRANT EXECUTE ON OBJECT::sp_XoaChiNhanh to doitac
GO

EXEC sp_addlogin 'QL_DH_GH_KHACHHANG', '12345', 'QL_DH_GH';  
GO

CREATE USER KHACHHANG FOR LOGIN QL_DH_GH_KHACHHANG
GO

grant select,insert,update 
on KHACHHANG
to KHACHHANG
--KH3
grant select
on DOITAC(EmailDT,TenQuan,SDTDT,DCKinhDoanh)
to KHACHHANG
--KH4
grant select
on QLThucDon(MieuTaMon,TinhTrangMon)
to KHACHHANG

grant select
on MON
to KHACHHANG
--KH5
grant select,insert
on DONHANG
to KHACHHANG
--KH6
grant select
on TAIXE(TENTX, SDTTX) 
to KHACHHANG
--KH7
grant select
on CHINHANH
to KHACHHANG

GRANT EXECUTE ON OBJECT::Sp_KH_MUASP TO KHACHHANG
GRANT EXECUTE ON OBJECT::Sp_KH_XEMSP TO KHACHHANG
GRANT EXECUTE ON OBJECT::sp_KH_XemDSDoiTac TO KHACHHANG
GRANT EXECUTE ON OBJECT::Sp_KH_DoiThongTinTK TO KHACHHANG
GRANT EXECUTE ON OBJECT::sp_KH_XemDSChiNhanh TO KHACHHANG
-- TAIXE
EXEC sp_addlogin 'QL_DH_GH_TAIXE', '12345', 'QL_DH_GH';  
GO

CREATE USER TAIXE FOR LOGIN QL_DH_GH_TAIXE
GO

--TX2
grant select,insert,update 
on TAIXE
to TAIXE
--TX3
grant select
on DONHANG
to TAIXE

grant select
on KHACHHANG(IDKH, TENKH, SDTKH)
to TAIXE
--TX4
grant update
on DONHANG(IDTaiXe, TrangThaiVanCHuyen) 
to TAIXE

--4. NHAN VIEN
EXEC SP_ADDLOGIN 'QL_DH_GH_NHANVIEN', '12345', 'QL_DH_GH';
CREATE USER NHANVIEN FROM LOGIN QL_DH_GH_NHANVIEN
--3--
GRANT SELECT, UPDATE 
ON TAIKHOAN
TO NHANVIEN
--4--
GRANT SELECT
ON DOITAC
TO NHANVIEN

GRANT SELECT
ON HOPDONG
TO NHANVIEN
--5--

GRANT UPDATE
ON HOPDONG(TrangThaiDuyet, NgayBatDau, NgayKetThuc) 
TO NHANVIEN

GRANT EXECUTE ON OBJECT::SP_DUYETHOPDONG1 TO NHANVIEN
GRANT EXECUTE ON OBJECT::SP_DUYETHOPDONG2 TO NHANVIEN
GRANT EXECUTE ON OBJECT::CHANGE_PASSWORD TO NHANVIEN
GRANT EXECUTE ON OBJECT::Sp_NV_LayTongTinTK TO NHANVIEN


EXEC SP_ADDROLE 'USERS'

-- ADD THÊM USER VÀO ROLE NÀY
EXEC sp_addrolemember 'USERS', 'DOITAC'
EXEC sp_addrolemember 'USERS', 'KHACHHANG'
EXEC sp_addrolemember 'USERS', 'TAIXE'
EXEC sp_addrolemember 'USERS', 'NHANVIEN'

-- CẤP QUYỀN CHO ROLE
GRANT SELECT, UPDATE ON TAIKHOAN(PASSWORD) TO USERS
GRANT EXECUTE ON OBJECT::SP_DANGNHAPKH TO USERS